de-id/agents-sdk

- package.json
- src/lib/createAgentManager.ts
> Throw error on chat creation

- src/createStreamingManager.ts
- yarn.lock
> added preact+preset-vite + type removed

- src/types/entities/agents/agent.ts
I added 'metdata' optional field which includes the user plan to Agent interface.
https://app.asana.com/0/1206103669096859/1206423147319126/f
> adding metadata to Agent inteface

- src/types/entities/agents/agent.ts
🔮 Feature
- Allow custom greetings for agents
-   [Asana](https://app.asana.com/0/1206103669096859/1206687857442910/f)
-   [Relevant PR in agents-ui] (https://github.com/de-id/agents-ui/pull/31)
-   [Relevant PR in studio] (https://github.com/de-id/studio/pull/2852)
-   [Relevant PR in serverless] (https://github.com/de-id/serverless/pull/2932)
> Add custom greetings to agent type

- demo/app.tsx
- src/api/knowledge.ts
- src/api/ratings.ts
- src/auth/getAuthHeader.ts
- src/connectToSocket.ts
- src/createAgentManager.ts
- src/createStreamingManager.ts
- src/index.ts
- src/types/StreamScript.ts
- src/types/entities/agents/chat.ts
- src/types/entities/agents/manager.ts
- yarn.lock
Refactor code and update dependencies
https://app.asana.com/0/1206767926855257/1206800703386020
> Refactor code and update dependencies

- demo/app.tsx
- package.json
- src/auth/getAuthHeader.ts
- src/connectToSocket.ts
- src/createAgentManager.ts
- src/createStreamingManager.ts
- src/services/mixpanel.ts
- src/types/entities/agents/chat.ts
- src/types/entities/agents/manager.ts
- src/types/stream/stream.ts
> Add Connect + change rate

- src/createStreamingManager.ts
apply idle streaming fallback to talks only
> apply idle streaming fallback to talks only

- src/connectToSocket.ts
- src/createAgentManager.ts
- src/createStreamingManager.ts
> Change tracks

- demo/app.tsx
- src/api/clipStream.ts
- src/api/talkStream.ts
- src/createAgentManager.ts
- src/types/stream/api/clip.ts
- src/types/stream/api/talk.ts
verified that stream_warmup is sent on streams post request
> ask for stream warmup

- src/createAgentManager.ts
1. refactor
2. ignore partials after answer received
> fix assistant message concatenation 

- src/api/talkStream.ts
- src/createAgentManager.ts
- src/types/stream/api/talk.ts
- adding compatibility mode for talk stream request 
- stitch -  higher resolution
https://app.asana.com/0/1207022934845348/1207071506477625/f
https://app.asana.com/0/1207022934845348/1207113457754786/f
> stitch high resolution + H264 codec

- src/createAgentManager.ts
🐛 BugFix
- Text wasn't always appearing for agent response
-   [Asana](https://app.asana.com/0/1207022934845348/1207214358444659/f)
> Create message before response

- src/createAgentManager.ts
- src/types/entities/agents/manager.ts
- adding stream resolution configuration for sdk users
- agents use 1080 for stitch as default
> adding stream resolution option in create stream

- src/api/talkStream.ts
- src/createAgentManager.ts
- src/types/entities/agents/manager.ts
- src/types/stream/api/talk.ts
- renaming: stream_resolution -> output_resolution
> stream_resolution -> output resolution

- demo/app.tsx
- src/createAgentManager.ts
- src/createStreamingManager.ts
- src/types/entities/agents/manager.ts
- src/types/stream/stream.ts
- sensitive to stream start
- fixing the cutoff bug
- https://app.asana.com/0/1207192568376365/1207237906837102/f
- @benyael15 don't merge yet, I want to check with you the stats to mixpanel..
> setting stats interval to 100ms

- infra/build.js
- src/createAgentManager.ts
> fixing default greeting

- src/createAgentManager.ts
sends tons of unnecessary data
https://d-id-api.sentry.io/issues/4925552627/events/27263caee342451db7ea1933a75a0c3e/
> dont send the matches back to chat

- src/services/mixpanel.ts
- src/utils/analytics.ts
Have agent type be clip-v2 if agent is dvp for analytics
> Change agent type to accomodate clips v2

- src/api/agents.ts
- src/createAgentManager.ts
- src/types/entities/agents/agent.ts
- [Asana](https://app.asana.com/0/1207922108504705/1207861165820789/f)
> Pass persist to create chat

- src/createAgentManager.ts
- src/types/entities/agents/manager.ts
- [Asana](https://app.asana.com/0/1207922108504705/1207377019853664/f)
> Optionally get initial messages injected

- src/createAgentManager.ts
- when connection is not established in 20sec, we retry. 
- max retries of 3
> Workaround/implement connectWithRetry as a workaround for unsuccessfully streams

- demo/app.tsx
- src/createAgentManager.ts
- src/services/mixpanel.ts
Fix analytics options passed with wring prop name
> fix analytics props

- package.json
- src/createAgentManager.ts
- src/services/mixpanel.ts
- src/types/entities/agents/manager.ts
- [Asana](https://app.asana.com/0/1209024070199682/1208687044775339/f)
> Feature/ Expose enrich mixpanel function

- package.json
- src/api/getClient.ts
- src/createAgentManager.ts
- src/utils/retryOperation.ts
- Fix stream opened for textonly
- add retry mechanism for 429 requests
> Bugfix / Fix stream opened for textonly & add retry mechanism for 429 requests

- src/createAgentManager.ts
- Bugfix: record messageSentTimestamp in speak
> record messageSentTimestamp on speak

- src/services/agent-manager/index.ts
- src/types/stream/api/clip.ts
passing to the speak method the chat id and the agent id to charge credits
> feature: charge credits for speak

- demo/hooks/useAgentManager.ts
- src/services/agent-manager/connect-to-manager.ts
- src/services/agent-manager/index.ts
- src/services/streaming-manager/index.ts
- src/services/streaming-manager/stats/report.ts
- src/types/entities/agents/manager.ts
- src/types/stream-script.ts
- src/types/stream/rtc.ts
- src/types/stream/stream.ts
Task: https://app.asana.com/1/856614567666442/project/1209921650299098/task/1209210693250775?focus=true
- Added a `streamType` of `Leagacy`/`Fluent` that returned from the create stream
- Added a new callback of `onAgentStateChange` that reflects streaming/idle
- disabled warmup when for fluent
> feature: fluent streaming

- src/services/agent-manager/index.ts
- src/types/entities/agents/manager.ts
> bugfix: remove default stream type

- src/services/agent-manager/connect-to-manager.ts
Adding e2e analytics for fluent
> feature: fluent latency analytics

- demo/app.tsx
- demo/hooks/useAgentManager.ts
- src/api/streams/clipStream.ts
- src/api/streams/talkStream.ts
- src/services/agent-manager/connect-to-manager.ts
- src/services/agent-manager/index.ts
- src/services/chat/intial-messages.ts
- src/services/streaming-manager/index.ts
- src/services/streaming-manager/stats/poll.ts
- src/types/entities/agents/manager.ts
- src/types/stream/stream.ts
- Greeting is handled only by agents ui
- To see the greeting message in the chat, instead of "initial messages" mechanism I added that when we do .speak - it will add it to the chat messages
> chore: remove greeting

- src/auth/get-auth-header.ts
- src/services/analytics/mixpanel.ts
- src/utils/index.ts
https://github.com/de-id/agents-sdk/security/code-scanning/2
> window.crypto

- src/services/streaming-manager/factory.test.ts
- src/services/streaming-manager/factory.ts
- src/services/streaming-manager/index.ts
Its simplest and fastest fix for now to make studio and agents-ui working again. 
When livekit was not commented out, agents-ui was not working during second load.
> livekit commented
